# Generated by Django 5.2.8 on 2025-12-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_product_category_saveditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('grains', 'Grains'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('livestock', 'Livestock'), ('tubers', 'Tubers')], max_length=50),
        ),
    ]
