# Generated by Django 5.2.8 on 2025-12-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_advisorytip_consultationrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvisoryTip',
        ),
    ]
